name: Integration tests

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:8-jdk-alpine
    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: atsd
          POSTGRES_PASSWORD: atsd
          POSTGRES_DB: atsd_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Install Maven
        run: apk add --no-cache maven
      - name: Launch tests with Maven
        run: mvn test -D spring.profiles.active=postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          DB_USER: atsd
          DB_PASSWD: atsd
